"""initial schema

Revision ID: c9ccbed9973a
Revises: 
Create Date: 2026-05-22 15:15:10.426194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9ccbed9973a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_email'), 'blacklist', ['email'], unique=True)
    op.create_table('urls',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url_hash', sa.String(length=64), nullable=False),
    sa.Column('current_risk_score', sa.Integer(), nullable=True),
    sa.Column('current_risk_level', sa.Enum('SAFE', 'WARNING', 'DANGER', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_normalized_url_hash'), 'urls', ['normalized_url_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LOCKED', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('admin_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('url_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CRAWLING', 'ANALYZING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('final_risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_url_id'), 'analysis_jobs', ['url_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('url_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fraud_type', sa.Enum('NON_DELIVERY', 'FALSE_ADVERTISING', 'REFUSAL_OF_REFUND', 'DEFECTIVE_PRODUCTS', 'PERSONAL_DATA_LEAKAGE', 'OTHERS', name='fraudtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_image_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACTIVE', 'UNDER_REVIEW', 'VERIFIED', 'BLINDED_DELETED', 'PENDING', 'HIDDEN', name='reportstatus'), nullable=False),
    sa.Column('legal_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_url_id'), 'reports', ['url_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_url_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_analysis_jobs_url_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_normalized_url_hash'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_blacklist_email'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
